---
- name: import the MongoDB public GPG key into apt
  apt_key:
    id: 7F0CEB10
    keyserver: keyserver.ubuntu.com
- name: Create the MongoDB source list
  shell: 'echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list'
  register: out
- name: Check MongoDB source list output
  debug: 
    var: out.stdout_lines
- name: Install the latest stable version of MongoDB
  apt: name={{ mongo }} state=present update_cache=yes
- name: Check mongod status
  shell: 'service mongod status'
  register: status
- debug: 
    var: status.stdout_lines
